image: node:18.19.0
definitions:
  caches:
    npm: ~/.npm
pipelines:
  branches:
    'web/development':
      - step:
          name: Web Development - creating build and deploy to aws
          deployment: DEV_WEB
          caches:
            - npm
          script:
            - cp .env.staging .env
            - rm -rf .env.staging
            - rm -rf .env.development
            - npm install --legacy-peer-deps
            - npm run build
            - rm -rf node_modules
            - rm -rf src
            - rm -rf .gitignore
            - rm -rf bitbucket-pipelines.yml
            - rm -rf README.md
            - git status
            - git fetch --unshallow || git fetch
            - git add --all
            - git commit -m "new build"
            - git push $REMOTE_DEV_WEB HEAD:web/development --force --no-thin
            - echo "Pushed RA WEB to aws in DEV Environment"
